#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate `docs/progress.md` -- the project's progress chart -- from the tree.

# Why this exists

`TRACKER.md` is the single source of truth for status and it is over four
thousand lines of prose. That is deliberate: the reasoning is the valuable part
and it does not compress. But it means nobody -- including the person running
the project -- can look at it and say where the work is, what is planned, and
what is finished. A source of truth nobody can hold in their head is still a
source of truth, and it is not project management.

So this builds the *view*. `TRACKER.md` stays authoritative; `docs/progress.md`
is generated from it and from the RFC headers, and is regenerated by `make
progress`. A gate fails when it is stale, so the chart cannot quietly drift
from the tracker the way three documents drifted from a boot report on
2026-08-25.

# Where every number comes from, and the one rule

**No date is invented.** Every date here is read from something that recorded
it:

  * an RFC's **start** is the date its file was first committed (`git log
    --diff-filter=A`), which is when the work became real in this tree;
  * an RFC's **end** is the acceptance date written in its own `Status` row;
  * a Phase 2 bullet's completion date is the one `TRACKER.md` states;
  * milestone rows carry no dates at all, so they are **counted, not charted**,
    and this file says so rather than drawing a plausible bar.

Anything undated is listed as undated. A Gantt chart that guesses is worse than
prose that admits it does not know.
"""

from __future__ import annotations

import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRACKER = ROOT / "TRACKER.md"
RFC_DIR = ROOT / "docs" / "rfc"
OUT = ROOT / "docs" / "progress.md"

# The date the first commit landed, used only as the chart's left edge.
PROJECT_START = "2026-08-03"


@dataclass
class Rfc:
    annex: bool
    number: str
    title: str
    subsystem: str
    started: str | None
    accepted: str | None
    state: str  # accepted | open | closed


def run(*args: str) -> str:
    """A git command, or an empty string when git has nothing to say."""
    try:
        return subprocess.run(
            args, cwd=ROOT, capture_output=True, text=True, check=False
        ).stdout.strip()
    except OSError:
        return ""


def first_commit_date(path: Path) -> str | None:
    """When this file entered the tree, which is when the work became real.

    **`None` for a file that is not committed yet, and that is a trap worth
    knowing about.** Generating this chart while a new RFC is still untracked
    dates it `-`; committing the RFC and the chart together then leaves a
    `docs/progress.md` that CI regenerates differently, and the invariants job
    goes red on a change that had nothing wrong with it. It did on 2026-08-27,
    for RFC 0050.

    So: **commit the RFC file first, then `make progress`, then commit the
    chart** -- or run `make progress` a second time after committing and amend.
    The gate is doing its job either way; this note exists so the next person
    spends a minute rather than a CI round trip working out why.
    """
    out = run(
        "git", "log", "--diff-filter=A", "--format=%ad", "--date=short", "--", str(path)
    )
    return out.split("\n")[-1] if out else None


def warn_if_untracked(path: Path, when: str | None) -> None:
    """Says so, loudly, when an RFC has no commit date yet.

    **A comment was tried first and did not work.** `first_commit_date` has
    carried a note since earlier on 2026-08-27 saying to commit the RFC before
    generating this chart, and the same mistake was made again nine commits
    later: the chart was generated in the same command that staged the file, so
    the RFC was still untracked and got a dash. CI regenerates it with the file
    committed, finds a date, and the invariants job goes red on a change with
    nothing wrong with it -- twice in one day, ten minutes each time.

    So the tool now says it at the moment it happens, where the person is
    looking, instead of leaving it to a gate a push away.
    """
    if when is None:
        print(
            f"  note  {path.name} is not committed yet, so it has no date and this "
            "chart will not match the one CI generates.\n"
            "        Commit the RFC first, then run `make progress` again.",
            file=sys.stderr,
        )


def status_row(text: str) -> str:
    for line in text.split("\n"):
        if line.startswith("| **Status**"):
            return line
    return ""


def field(text: str, name: str) -> str:
    for line in text.split("\n"):
        if line.startswith(f"| **{name}**"):
            parts = line.split("|")
            if len(parts) > 2:
                return parts[2].strip()
    return ""


def clean(s: str) -> str:
    """Plain text: no markup, and nothing Mermaid parses as syntax."""
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", s)
    s = s.replace("**", "").replace("`", "").replace("~~", "")
    s = s.replace(":", " -").replace(",", " ").replace(";", " ")
    s = re.sub(r"\s+", " ", s)
    return s.strip()


# Subsystem rows are prose -- "kernel/iommu, kernel/lib.rs bring-up" and worse
# -- so the first word of one is not a section name. The first attempt at this
# file took it anyway and produced a Gantt section called "A", twice.
THEMES: list[tuple[str, tuple[str, ...]]] = [
    ("Boot & firmware", ("boot", "loader", "uefi", "efi", "limine", "paging")),
    ("Filesystem & storage", ("fs", "vfs", "filesystem", "ustar", "disk",
                              "journal", "block", "storage", "ahci", "sata")),
    ("Capabilities & IPC", ("cap", "ipc", "domain", "syscall", "nucleus",
                            "service", "notification")),
    ("Networking", ("net", "tcp", "udp", "ipv4", "ipv6", "socket", "dhcp",
                    "arp", "sock")),
    ("Drivers & IOMMU", ("driver", "iommu", "vtd", "xhci", "usb", "pci",
                         "virtio", "device", "keyboard", "irq", "console")),
    ("Memory & scheduling", ("mm", "memory", "sched", "thread", "smp", "time",
                             "timer", "frame")),
    ("Userspace & personality", ("userspace", "user", "shell", "personality",
                                 "linux", "libc", "package", "supervisor",
                                 "elf", "program")),
    ("Process & tooling", ("docs", "process", "tools", "governance", "licence",
                           "license", "telemetry", "ai", "ci")),
]


def score(hay: str) -> tuple[int, str] | None:
    """The best-matching theme for a blob of text, and how well it matched."""
    best: tuple[int, str] | None = None
    for name, words in THEMES:
        hits = sum(1 for w in words if re.search(rf"\b{w}\b", hay))
        if hits and (best is None or hits > best[0]):
            best = (hits, name)
    return best


def theme(subsystem: str, title: str) -> str:
    """Which section of the chart an RFC belongs in.

    **Scored, not first-match.** Several RFCs name three or four subsystems --
    `kernel/domain, kernel/sched, kernel/trap, kernel/ipc` -- and the first
    keyword to hit is not the one that describes the work. Counting matches
    puts that RFC under capabilities rather than under scheduling because three
    of its four subsystems are capability-shaped.

    The **subsystem row decides**, and the title is consulted only when the row
    matches nothing. An earlier version searched both at once and filed the
    system-call and IPC interface under networking, because `ip` occurs inside
    `IPC`. Ties go to the order above.
    """
    return (
        (score(subsystem.lower()) or score(title.lower()) or (0, "Kernel"))[1]
    )


def read_rfcs() -> list[Rfc]:
    found: list[Rfc] = []
    for path in sorted(RFC_DIR.glob("[0-9][0-9][0-9][0-9]-*.md")):
        number = path.name[:4]
        if number == "0000":
            continue  # the template is not work
        text = path.read_text(encoding="utf-8")

        heading = next(
            (l for l in text.split("\n") if l.startswith("# ")), f"# RFC {number}"
        )
        # **An annex is not an RFC.** `docs/rfc/` holds companion documents that
        # share their parent's number -- `# RFC 0040 step 1 -- the libcrux
        # inspection` beside `# RFC 0040: Where cryptography comes from`. A
        # heading with a colon after the number is the RFC; anything else
        # sharing that number is an annex, and counting it as a second RFC
        # inflated the open count by one until this was noticed.
        is_annex = not re.match(r"^#\s*RFC\s*\d+\s*:", heading)
        title = re.sub(r"^#\s*RFC\s*\d+\s*:?\s*", "", heading).strip() or number

        row = status_row(text)
        accepted = None
        # `Accepted 2026-08-04`, `**Accepted** — 2026-08-02`, `ACCEPTED
        # 2026-08-25`: the date follows the word but not always immediately,
        # because markup and an em-dash can sit between them. Bounded so this
        # cannot reach a date in a later sentence.
        match = re.search(
            r"accepted\b[^0-9]{0,16}(\d{4}-\d{2}-\d{2})", row, re.IGNORECASE
        )
        if match:
            accepted = match.group(1)

        low = row.lower()
        if accepted:
            state = "accepted"
        elif "superseded" in low or "closed without" in low or "rejected" in low:
            state = "closed"
        else:
            state = "open"

        started = first_commit_date(path)
        warn_if_untracked(path, started)
        found.append(
            Rfc(
                annex=is_annex,
                number=number,
                title=title,
                subsystem=theme(field(text, "Subsystem"), title),
                started=started,
                accepted=accepted,
                state=state,
            )
        )
    return found


def read_milestones(text: str) -> dict[str, tuple[int, int]]:
    """Milestone rows, grouped by their M-number. `(done, total)`."""
    groups: dict[str, tuple[int, int]] = {}
    for match in re.finditer(r"^\|\s*(M\d+)-[0-9a-z]+\s*\|.*?\|\s*(✅|⬜|🔨)", text, re.M):
        group, mark = match.group(1), match.group(2)
        done, total = groups.get(group, (0, 0))
        groups[group] = (done + (1 if mark == "✅" else 0), total + 1)
    return groups


def read_phase_bullets(text: str) -> list[tuple[str, bool, str | None]]:
    """The Phase 2 table: what the bullet is, whether it is done, and when."""
    bullets: list[tuple[str, bool, str | None]] = []
    section = text.split("## 4. Upcoming work", 1)
    if len(section) < 2:
        return bullets
    body = section[1].split("\n## ", 1)[0]
    for line in body.split("\n"):
        if not line.startswith("|") or line.startswith("|---") or "Phase 2 bullet" in line:
            continue
        cells = line.split("|")
        if len(cells) < 4:
            continue
        name, status = clean(cells[1]), cells[2]
        if not name:
            continue
        when = re.search(r"(\d{4}-\d{2}-\d{2})", status)
        bullets.append((name, "✅" in status, when.group(1) if when else None))
    return bullets


def bar(rfc: Rfc, today: str) -> str | None:
    """One Gantt row, or `None` when there is no honest date for it."""
    if not rfc.started:
        return None
    label = f"RFC {rfc.number} {clean(rfc.title)}"
    if len(label) > 58:
        # Trim at a word boundary. Cutting mid-word reads as a broken file
        # rather than as a long title.
        label = label[:58].rsplit(" ", 1)[0] + "..."
    ident = f"r{rfc.number}"
    if rfc.state == "accepted" and rfc.accepted:
        # A one-day bar when the file arrived and was accepted the same day --
        # which happens, and is a real fact about this project rather than a
        # rounding error. Two RFCs were accepted the day *before* their file
        # was committed; those clamp to a day too rather than drawing backwards.
        end = max(rfc.accepted, rfc.started)
        if end == rfc.started:
            return f"    {label} :done, {ident}, {rfc.started}, 1d"
        return f"    {label} :done, {ident}, {rfc.started}, {end}"
    if rfc.state == "closed":
        return f"    {label} :crit, {ident}, {rfc.started}, 1d"
    return f"    {label} :active, {ident}, {rfc.started}, {max(today, rfc.started)}"


def newest_recorded(tracker: str, rfcs: list["Rfc"]) -> str:
    """The newest date `TRACKER.md` and the RFC headers actually record.

    Used as the right-hand end of every *open* RFC bar, and reported as the
    chart's own high-water mark. Deliberately not the wall clock and not
    `HEAD`'s date -- see the note in `render`.

    Falls back to the project start when nothing is found, which keeps a
    malformed tracker from producing a chart with no time axis at all.
    """
    # **Dated changelog headings and RFC acceptances, and nothing else.**
    #
    # Not every date in the file: the first draft of this swept up *every*
    # `20xx-xx-xx` in the tracker and came back with **2026-11-29**, which is
    # the planned first release -- a date recording an intention, not work. It
    # would have drawn every open bar four months into the future. A heading
    # and an acceptance are both records of something that happened; a plan is
    # not, and this file draws only what happened.
    dates = re.findall(r"(?m)^###\s+(20\d\d-[01]\d-[0-3]\d)", tracker)
    dates += [r.accepted for r in rfcs if r.accepted]
    real = [d for d in dates if d]
    return max(real) if real else PROJECT_START


def render() -> str:
    tracker = TRACKER.read_text(encoding="utf-8")
    every = read_rfcs()
    rfcs = [r for r in every if not r.annex]
    annexes = [r for r in every if r.annex]
    milestones = read_milestones(tracker)
    bullets = read_phase_bullets(tracker)
    # **The open bars end at the newest date the *tracker* records, not at the
    # newest commit.**
    #
    # It used to be `git log -1 --date=short`, and that made this file
    # unsatisfiable for the first commit of any day. Every open RFC's bar ends
    # at this date, so the chart legitimately changes the moment HEAD's date
    # changes -- and an author cannot regenerate a chart containing their own
    # commit's date *before* that commit exists. The gate then fails on a
    # commit nobody could have made correctly. It did, on run 345: `67b2cba`
    # was the first commit after midnight, its chart said 2026-08-25, the gate
    # regenerated 2026-08-26, and called it stale. Correctly, and uselessly.
    #
    # A date out of `TRACKER.md` has neither problem. It moves only when the
    # tracker records a new one, which happens in the same commit that
    # regenerates this file -- so the rule "regenerate when the tracker
    # changes" becomes something a person can actually obey. And it keeps this
    # file's own promise that no date here is invented: wall-clock time would
    # have fixed the gate by inventing exactly the kind of date the header
    # refuses to draw.
    latest = newest_recorded(tracker, every)

    accepted = [r for r in rfcs if r.state == "accepted"]
    openish = [r for r in rfcs if r.state == "open"]
    closed = [r for r in rfcs if r.state == "closed"]
    undated = [r for r in rfcs if not r.started]

    out: list[str] = []
    add = out.append

    add("# Bhaskix progress")
    add("")
    add(
        "**Generated by `tools/progress.py` — do not edit.** Run `make progress` "
        "after changing `TRACKER.md`; `make gates` fails when this file is stale."
    )
    add("")
    add(
        "*What that gate proves, exactly:* that this file **matches** what the "
        "tracker and the RFC headers currently say — not that anyone "
        "regenerated it. A tracker edit that changes only prose leaves this "
        "file identical and the gate green, which is correct: nothing here "
        "went stale. The gate bites when a count, a date or a status moves."
    )
    add("")
    add(
        "[`TRACKER.md`](../TRACKER.md) is the source of truth and stays so. This "
        "is the view of it: what is finished, what is in flight, and when. "
        "**No date here is invented** — an RFC's bar starts the day its file "
        "entered the tree and ends the day its own `Status` row says it was "
        "accepted. Work with no recorded date is counted below rather than drawn."
    )
    add("")

    add("## Where the project is")
    add("")
    add("| | |")
    add("|---|---|")
    add(f"| RFCs accepted | **{len(accepted)}** |")
    add(f"| RFCs open | {len(openish)} |")
    add(f"| RFCs closed without shipping | {len(closed)} |")
    done_total = sum(d for d, _ in milestones.values())
    all_total = sum(t for _, t in milestones.values())
    add(f"| Milestone rows done | **{done_total} of {all_total}** |")
    finished = sum(1 for _, ok, _ in bullets if ok)
    add(f"| Phase 2 bullets done | **{finished} of {len(bullets)}** |")
    add(f"| Newest dated entry | {latest} |")
    add("")

    add("## Timeline")
    add("")
    add(
        "Bars are **real intervals**: file created → accepted. A bar is not an "
        "estimate of effort, and an RFC accepted the day it was drafted shows as "
        "a single day because that is what happened."
    )
    add("")
    add("```mermaid")
    add("gantt")
    add("    title Bhaskix — RFCs from draft to acceptance")
    add("    dateFormat YYYY-MM-DD")
    add("    axisFormat %d %b")
    add("    todayMarker off")

    sections: dict[str, list[Rfc]] = {}
    for rfc in rfcs:
        sections.setdefault(rfc.subsystem, []).append(rfc)

    order = [n for n, _ in THEMES] + ["Kernel"]
    for name in sorted(sections, key=lambda n: order.index(n) if n in order else 99):
        rows = [bar(r, latest) for r in sorted(sections[name], key=lambda r: r.number)]
        rows = [r for r in rows if r]
        if not rows:
            continue
        add(f"    section {name}")
        out.extend(rows)
    add("```")
    add("")
    add(
        "`done` is accepted, `active` is open, `crit` is closed without shipping."
    )
    add("")

    add("## Milestones")
    add("")
    add(
        "`TRACKER.md`'s milestone rows carry **no dates**, so they are counted "
        "rather than charted. Inventing start dates to make a prettier picture "
        "is exactly what this file refuses to do."
    )
    add("")
    lowest = min((int(g[1:]) for g in milestones), default=0)
    if lowest > 1:
        add(
            f"**M1–M{lowest - 1} have no rows in the tracker** and so are absent "
            "from this table. They are not missing work: the detail table starts "
            f"at M{lowest}, and the earlier milestones are summarised in the "
            "tracker's own progress cell. Their absence here is a property of "
            "the source, said out loud rather than left to read as zero."
        )
        add("")
    add("")
    add("| Milestone | Done | Total | |")
    add("|---|---:|---:|---|")
    for group in sorted(milestones, key=lambda g: int(g[1:])):
        done, total = milestones[group]
        filled = round(10 * done / total) if total else 0
        add(f"| {group} | {done} | {total} | {'█' * filled}{'░' * (10 - filled)} |")
    add("")

    add("## Phase 2 bullets")
    add("")
    add("| Bullet | Status | Recorded date |")
    add("|---|---|---|")
    for name, ok, when in bullets:
        add(f"| {name} | {'✅ done' if ok else '⬜ open'} | {when or '—'} |")
    add("")

    if openish:
        add("## Open RFCs")
        add("")
        add("| RFC | Title | Started |")
        add("|---|---|---|")
        for rfc in sorted(openish, key=lambda r: r.number):
            add(f"| {rfc.number} | {clean(rfc.title)} | {rfc.started or '—'} |")
        add("")

    if annexes:
        add("## Annexes")
        add("")
        add(
            "Companion documents that share an RFC's number. Counted here "
            "rather than as RFCs of their own."
        )
        add("")
        for rfc in sorted(annexes, key=lambda r: r.number):
            add(f"- RFC {rfc.number} — {clean(rfc.title)}")
        add("")

    if undated:
        add("## Undated")
        add("")
        add(
            "No commit adding these files was found, so they have no start date "
            "and are not on the chart."
        )
        add("")
        for rfc in undated:
            add(f"- RFC {rfc.number} — {clean(rfc.title)}")
        add("")

    return "\n".join(out) + "\n"


def shallow() -> bool:
    """Whether this clone has been truncated, which breaks every start date.

    **The failure mode this exists to name.** Start dates come from the commit
    that added each RFC file, so a shallow clone -- which is what
    `actions/checkout` produces by default -- computes different dates from a
    full one and makes `--check` fail with a diff that has nothing to do with
    the change under test. That happened on `13a7faf`. CI now fetches full
    history; this says so out loud when it does not, instead of leaving
    somebody to work it out from a wall of changed dates.
    """
    return run("git", "rev-parse", "--is-shallow-repository") == "true"


def main() -> int:
    if shallow():
        print(
            "this is a shallow clone, so no RFC start date can be computed.\n"
            "  `docs/progress.md` dates each RFC from the commit that added its\n"
            "  file; fetch full history (`fetch-depth: 0`, or `git fetch\n"
            "  --unshallow`) before generating or checking it.",
            file=sys.stderr,
        )
        return 1
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists():
            print(f"{OUT.relative_to(ROOT)} does not exist; run `make progress`")
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(
                f"{OUT.relative_to(ROOT)} is stale -- TRACKER.md or an RFC header "
                "changed without it. Run `make progress`."
            )
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
